### User Registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@example.com",
    "password": "password"
}

### User Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user2@example.com",
    "password": "password"
}

### User Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjliM2I4YTk4LTVhOTctNDY0Zi1hM2FmLTY2OTI1YWE4NmM4NiIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mjg5NzQ2NDcsImV4cCI6MTcyODk3ODI0N30.nJ4lmbqGC-EdqrLaLoUVGiKGE-ChShz1YM1oPYIlER4

{
    "email": "user1@example.com"
}

### Create a new chat
POST http://localhost:3000/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3ZjVhNjZkLWFkNDUtNGVkNS1hOTNlLTMyMzgwOWY3NjBjMyIsImVtYWlsIjoidXNlcjJAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjkwMDQzMzIsImV4cCI6MTcyOTAwNzkzMn0.HqBzg3EYrcZgjyZkQXGyw0JZEWl6yyEXkNM4ZvrRRw4

{
    "users": ["d7f5a66d-ad45-4ed5-a93e-323809f760c3", "8e02905e-b1db-45fd-81f4-e1b37fe0c320"]
}